name: cd

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
    
    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22"
      
      - name: Install Goose Migration Tool
        run: |
          go install github.com/pressly/goose/v3/cmd/goose@latest
          echo "$HOME/go/bin" >> $GITHUB_PATH

      - name: Build app
        run: ./scripts/buildprod.sh
      
      - name: Run Database Migrations
        run: ./scripts/migrateup.sh
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - id: "auth"
        name: Authenticate with Google Cloud
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v2" # Updated version

      - name: "Build the Docker image"
        # The "." at the end tells gcloud to look for the Dockerfile in the current directory
        run: gcloud builds submit --tag europe-west10-docker.pkg.dev/notely-484119/notely-ar-repo/my-app:latest .

      - name: Deploy to Cloud Run
        # run: gcloud run deploy notely --image REGION-docker.pkg.dev/PROJECT_ID/REPO_NAME/IMAGE:TAG --region REGION --allow-unauthenticated --project PROJECT_ID --max-instances=4
        run: |
          gcloud run deploy notely \
            --image europe-west10-docker.pkg.dev/notely-484119/notely-ar-repo/my-app:latest \
            --region us-central1 \
            --allow-unauthenticated \
            --project notely-484119 \
            --max-instances=4
